#! /usr/bin/python

"""Checks the CPU usage of a shared node"""

import nagiosplugin
import argparse

class SharedNodeCpu(nagiosplugin.Resource):

    def __init__(self, aggregate, host):
        self._aggregate = aggregate
        self._host = host 

    def probe(self):
        # Query the aggregator data store
        # FIXME: Fake data for now
        name = "%s_%s_sn_cpu" % (self._aggregate, self._host)
        value = 0

        return [nagiosplugin.Metric(name, value, min=0, context='load')]

@nagiosplugin.guarded
def main():
    argp = argparse.ArgumentParser(description=__doc__)
    argp.add_argument('-w', '--warning', metavar='RANGE', default='',
                      help='return warning if load is outside RANGE')
    argp.add_argument('-c', '--critical', metavar='RANGE', default='',
                      help='return critical if load is outside RANGE')
    argp.add_argument('-a', '--aggregate',
                      help='identifier for aggregate to check')
    argp.add_argument('-s', '--host',
                      help='identifier for host to check')
    args = argp.parse_args()
    check = nagiosplugin.Check(
        SharedNodeCpu(args.aggregate, args.host),
        nagiosplugin.ScalarContext('load', args.warning, args.critical))
    check.main()

if __name__ == '__main__':
    main()
