#! /usr/bin/python
#----------------------------------------------------------------------
# Copyright (c) 2014 Raytheon BBN Technologies
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and/or hardware specification (the "Work") to
# deal in the Work without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Work, and to permit persons to whom the Work
# is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Work.
#
# THE WORK IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE WORK OR THE USE OR OTHER DEALINGS
# IN THE WORK.
#----------------------------------------------------------------------

"""Checks the used amount of memory of a shared node"""

import nagiosplugin
import argparse

class SharedNodeMemUsed(nagiosplugin.Resource):

    def __init__(self, aggregate):
        self._aggregate = aggregate

    def probe(self):
        # Query the aggregator data store
        # FIXME: Fake data for now
        hosts = ['pc1', 'pc2', 'pc5']
        name = {}
        value = {}
        metric = []

        for host in hosts:
            name[host] = '%s_mem_used' % host
            value[host] = 0
            metric.append(nagiosplugin.Metric(name[host], value[host], min=0,
                                              context='mem'))

        return metric

@nagiosplugin.guarded
def main():
    argp = argparse.ArgumentParser(description=__doc__)
    argp.add_argument('-w', '--warning', metavar='RANGE', default='',
                      help='return warning if load is outside RANGE')
    argp.add_argument('-c', '--critical', metavar='RANGE', default='',
                      help='return critical if load is outside RANGE')
    argp.add_argument('-a', '--aggregate',
                      help='identifier for aggregate to check')
    args = argp.parse_args()
    check = nagiosplugin.Check(
        SharedNodeMemUsed(args.aggregate),
        nagiosplugin.ScalarContext('mem', args.warning, args.critical))
    check.main()

if __name__ == '__main__':
    main()
