#! /usr/bin/python

"""Checks the swap usage of a shared node"""

import nagiosplugin
import argparse

class SharedNodeSwapFree(nagiosplugin.Resource):

    def __init__(self, aggregate):
        self._aggregate = aggregate

    def probe(self):
        # Query the aggregator data store
        # FIXME: Fake data for now
        hosts = ['pc1', 'pc2', 'pc5']
        name = {}
        value = {}
        metric = []

        for host in hosts:
            name[host] = '%s_swap_free' % host
            value[host] = 4000
            metric.append(nagiosplugin.Metric(name[host], value[host], min=0,
                                              context='swapfree'))

        return metric

@nagiosplugin.guarded
def main():
    argp = argparse.ArgumentParser(description=__doc__)
    argp.add_argument('-w', '--warning', metavar='RANGE', default='',
                      help='return warning if load is outside RANGE')
    argp.add_argument('-c', '--critical', metavar='RANGE', default='',
                      help='return critical if load is outside RANGE')
    argp.add_argument('-a', '--aggregate',
                      help='identifier for aggregate to check')
    args = argp.parse_args()
    check = nagiosplugin.Check(
        SharedNodeSwapFree(args.aggregate),
        nagiosplugin.ScalarContext('swapfree', args.warning, args.critical))
    check.main()

if __name__ == '__main__':
    main()
